stages:
# Training Stage
  validation:
    cmd: python src/trainingRawDataValidation.py
    deps:
    - config/schema_training.json
    - Training_Batch_Files/Mushroom_Data_23042021_023412.csv
  
  transformation:
    cmd: python src/trainingRawDataTransformation.py
    deps:
    - data/Training_Raw_files_validated/Good_raw/Mushroom_Data_23042021_023412.csv
  
  dbinsertion:
    cmd: python src/trainingDatabaseOperations.py
    outs:
    - data/Training_FileFromDB/master.csv

  preprocessing:
    cmd: python src/trainingPreprocessing.py
    deps:
    - data/Training_FileFromDB/master.csv
    outs:
    - data/preprocessed_data/trainingPreprocessedData.csv

  model_training:
    cmd: python src/modeltraining.py
    deps:
    - data/preprocessed_data/trainingPreprocessedData.csv
    - src/clustering.py
    - src/model_methods.py
    - src/modeltuner.py
    - src/performLogging.py
    outs:
    - models

# Prediction Stage
  prediction_using_trained_models:
    cmd: python src/app.py
    deps:
    - src/predictionRawDataValidation.py
    - src/predictionRawDataTransformation.py
    - src/predictionDatabaseOperations.py
    - src/predictionPreprocessing.py
    - src/Predictions_using_trained_model.py
    outs:
    - Prediction_Output_File/Predictions.csv

